<?php
/*
 * UnifonicNextGenLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace UnifonicNextGenLib\Models;

use JsonSerializable;

/**
 *Gets details of specified message
 */
class GetMessageQueryResponse implements JsonSerializable
{
    /**
     * The message statues
     * @required
     * @maps STATUS05
     * @var string $sTATUS05 public property
     */
    public $sTATUS05;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $sTATUS05 Initialization value for $this->sTATUS05
     */
    public function __construct()
    {
        if (1 == func_num_args()) {
            $this->sTATUS05 = func_get_arg(0);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['STATUS05'] = $this->sTATUS05;

        return $json;
    }
}
