<?php
/*
 * UnifonicNextGenLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace UnifonicNextGenLib\Models;

use JsonSerializable;

/**
 *Sends message to one or more recipients.
 */
class SendWrapperResponse implements JsonSerializable
{
    /**
     * The default error code
     * @required
     * @maps Error
     * @var string $error public property
     */
    public $error;

    /**
     * A unique ID that identifies a message
     * @required
     * @maps MessageID
     * @var string $messageID public property
     */
    public $messageID;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $error     Initialization value for $this->error
     * @param string $messageID Initialization value for $this->messageID
     */
    public function __construct()
    {
        if (2 == func_num_args()) {
            $this->error     = func_get_arg(0);
            $this->messageID = func_get_arg(1);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['Error']     = $this->error;
        $json['MessageID'] = $this->messageID;

        return $json;
    }
}
