<?php
/*
 * UnifonicNextGenLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace UnifonicNextGenLib;

/**
 * Environments available for API
 */
class Environments
{
    /**
     * Describe the setting where software and other products are actually put into operation for their
     * intended uses by end users
     */
    const PRODUCTION = "production";
}
