<?php
/*
 * UnifonicNextGenLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace UnifonicNextGenLib;

use UnifonicNextGenLib\Controllers;

/**
 * UnifonicNextGenLib client class
 */
class UnifonicNextGenClient
{
    /**
     * Constructor with authentication and configuration parameters
     */
    public function __construct(
        $basicAuthUserName = null,
        $basicAuthPassword = null
    ) {
        Configuration::$basicAuthUserName = $basicAuthUserName ? $basicAuthUserName : Configuration::$basicAuthUserName;
        Configuration::$basicAuthPassword = $basicAuthPassword ? $basicAuthPassword : Configuration::$basicAuthPassword;
    }
    /**
     * Singleton access to Wrapper controller
     * @return Controllers\WrapperController The *Singleton* instance
     */
    public function getWrapper()
    {
        return Controllers\WrapperController::getInstance();
    }
    /**
     * Singleton access to Rest controller
     * @return Controllers\RestController The *Singleton* instance
     */
    public function getRest()
    {
        return Controllers\RestController::getInstance();
    }
}
